# Configuration

# Packages needed

library(readxl)
library(phyloseq)
library(vegan)
library(tidyverse)
library(microbiome)
library(MetBrewer)
library(showtext)
library(microbiomeutilities)
library(ade4)
library(CCA)
library(correlation)
library(eulerr)
library(ggpubr)
library(ggsci)
library(patchwork)
library(qiime2R)
library(ggfortify)
library(MoMAColors)
library(microeco)
library(file2meco)
library(reshape2)
library(microViz)
library(microbiomeMarker)
library(multcompView)
